#! /bin/bash

pop=$(cut -f4 -d' ' log.txt | cut -f1 -d':' | sort -k1 | uniq -c | sort -k1 | tail -10 | sed 's/\[//' | sed 's/ *//' | awk '{a=$1; $1=$2; $2=a; print}' | sed 's/\//-/g')
lines=$(cut -f4 -d' ' log.txt | wc -l)
arr=($pop)
for i in {1..20..2}; do echo ${arr[i-1]} - ${arr[i]} - $((arr[i]*100/$lines))%; done
